### ISSUE TITLE
Postgres fails with "Connection could not be created to" … "Possibly the wrong driver for the given database URL"

### ISSUE THREAD

**Issue by ctron** [liquibase/docker#129]
Trying to apply a simple schema to postgres fails with:

~~~
Caused by: liquibase.exception.DatabaseException: Connection could not be created to "jdbc:postgresql://timescaledb:5432/timescale?ssl=false" with driver org.postgresql.Driver.  Possibly the wrong driver for the given database URL
	at liquibase.database.jvm.JdbcConnection.open(JdbcConnection.java:46)
	at com.datical.liquibase.ext.database.jvm.ProJdbcConnection.open(Unknown Source)
	at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:32)
	... 31 more

~~~

However, the database is indeed PostgreSQL!!

I also don't see any cause above the shown error. So I am wondering what causes this error.

Version:

~~~
Starting Liquibase at 14:29:36 (version 4.5.0 #52 built at 2021-09-27 16:19+0000)
Liquibase Version: 4.5.0
Liquibase Community 4.5.0 by Datical
~~~

**Comment by arichiardi** [comment]
I have run into this as well, if the environment variable is quoted, liquibase returns:

```
[2022-07-18 20:38:35] SEVERE [liquibase.integration] Connection could not be created to 'jdbc:postgresql://localhost:5432/dbserver?user=user&password=secure&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory' with driver org.postgresql.Driver.  Possibly the wrong driver for the given database URL
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to 'jdbc:postgresql://localhost:5432/dbserver?user=user&password=secure&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory' with driver org.postgresql.Driver.  Possibly the wrong driver for the given database URL
```

**Comment by nikhiljiddigi** [comment]
Even I'm facing the same error, any alternative or hack around it would be helpful

**Comment by TheNotary** [comment]
I was getting this for house tonight but it was a typo!  

I had

```
jdbc:postgres://localhost:5432/database
```

but needed

```
jdbc:postgresql://localhost:5432/database
```

**Comment by jandroav** [comment]
Hi @ctron @arichiardi @nikhiljiddigi could you please share the exact command you were running?

**Comment by jnewton03** [comment]
Hi @ctron @arichiardi @nikhiljiddigi is this issue still valid or now stale?

**Comment by jnewton03** [comment]
closing as stale

**Comment by alex-ionita-takeda** [comment]
i am facing the same issue using a postgres container
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:postgresql://localhost:64546/initial with driver org.postgresql.Driver.  Connection to localhost:64546 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
