### ISSUE TITLE
Not able to run generateChangeLog on existing DB

### ISSUE THREAD

**Issue by vgshettigar** [liquibase/docker#159]
Tried many different ways to generate changelog on existing DB, no solution yet. 
I either get "permission denied" or "No such file or directory" 
Unexpected error running Liquibase: java.io.FileNotFoundException: /db/changelog.xml (No such file or directory)

This is the command I am running:
docker run --rm --net="host" -v /home/administrator/liquibase/HR/changelog:/liquibase/changelog liquibase/liquibase:latest --url="jdbc:sqlserver://xx.xx.xx.xx:1433;databaseName=liquibasedb;integratedSecurity=false;" --changeLogFile=db/changelog.xml --classpath=/liquibase/changelog --username="sa" --password="#####"  generateChangeLog

**Comment by rijnhard** [comment]
Yup, same issue. 

if i mount into either:
* expected directory `./myproject:/liquibase/changelog:rw`
 * with or without classpath explicitly set
 *  `--changeLogFile=changelog/blah.postgres.sql` (which doesn't exist)
* a random directory  `./myproject:/randomdir:rw`
 *  `--classpath=/randomdir`
 *  `--changeLogFile=/randomdir/blah.postgres.sql` (which doesn't exist)

the weird thing is it actually generates successfully if i just set a filename `--changeLogFile=blah.postgres.sql`  but this doesn't generate it into the mounted volume at `/liquibase/changelog`

more details on the error
```
[2022-12-13 14:19:19] INFO [liquibase.diff] changeSets count: 5
[2022-12-13 14:19:19] INFO [liquibase.diff] changelog/warehouse.postgres.sql does not exist, creating and adding 5 changesets.
[2022-12-13 14:19:19] WARNING [liquibase.resource] Failed to create parent directories for file changelog/warehouse.postgres.sql
[2022-12-13 14:19:19] SEVERE [liquibase.integration] changelog/warehouse.postgres.sql
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.nio.file.AccessDeniedException: changelog/warehouse.postgres.sql
        at liquibase.command.CommandScope.execute(CommandScope.java:178)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:352)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:317)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.nio.file.AccessDeniedException: changelog/warehouse.postgres.sql
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:260)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1587)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:396)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.integration.commandline.Main$1.run(Main.java:395)
        at liquibase.integration.commandline.Main$1.run(Main.java:217)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.Main.run(Main.java:217)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:33)
        at liquibase.command.CommandScope.execute(CommandScope.java:172)
        ... 20 more
Caused by: liquibase.exception.CommandExecutionException: java.nio.file.AccessDeniedException: changelog/warehouse.postgres.sql
        at liquibase.command.CommandScope.execute(CommandScope.java:178)
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:258)
        ... 33 more
Caused by: java.nio.file.AccessDeniedException: changelog/warehouse.postgres.sql
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
        at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
        at liquibase.resource.PathResource.openOutputStream(PathResource.java:92)
        at liquibase.diff.output.changelog.DiffToChangeLog.printNew(DiffToChangeLog.java:215)
        at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:136)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:130)
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:87)
        at liquibase.command.core.InternalGenerateChangelogCommandStep.run(InternalGenerateChangelogCommandStep.java:79)
        at liquibase.command.CommandScope.execute(CommandScope.java:172)
        ... 34 more


Unexpected error running Liquibase: changelog/warehouse.postgres.sql

liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.nio.file.AccessDeniedException: changelog/warehouse.postgres.sql
        at liquibase.command.CommandScope.execute(CommandScope.java:178)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:352)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:317)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.nio.file.AccessDeniedException: changelog/warehouse.postgres.sql
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:260)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1587)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:396)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.integration.commandline.Main$1.run(Main.java:395)
        at liquibase.integration.commandline.Main$1.run(Main.java:217)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.Main.run(Main.java:217)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:33)
        at liquibase.command.CommandScope.execute(CommandScope.java:172)
        ... 20 more
Caused by: liquibase.exception.CommandExecutionException: java.nio.file.AccessDeniedException: changelog/warehouse.postgres.sql
        at liquibase.command.CommandScope.execute(CommandScope.java:178)
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:258)
        ... 33 more
Caused by: java.nio.file.AccessDeniedException: changelog/warehouse.postgres.sql
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
        at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
        at liquibase.resource.PathResource.openOutputStream(PathResource.java:92)
        at liquibase.diff.output.changelog.DiffToChangeLog.printNew(DiffToChangeLog.java:215)
        at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:136)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:130)
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:87)
        at liquibase.command.core.InternalGenerateChangelogCommandStep.run(InternalGenerateChangelogCommandStep.java:79)
        at liquibase.command.CommandScope.execute(CommandScope.java:172)
        ... 34 more
```

**Comment by rmcelroy-hylaine** [comment]
I'll echo this. Absolutely cannot get this docker container to work in terms of generating an intial or updated changeset to a file on my host.

It also won't reference liquibase.properties correctly either. If I don't provide connection information then the command will fail looking for the URL, Username, and password.

I've tried specifying the volume path completely, referencing it with `${PWD}` in powershell, etc. Even when executing the docker command that supposedly executes fully I see no changeset file in the container or the host.

Directory that I'm executing from the powershell CLI: `C:\Projects\Demo\DevOps\Liquibase`

Example command: `docker run --rm --network=host -v ${PWD}/changeset:/liquibase/changeset liquibase/liquibase --defaultsFile="liquibase.properties" --changeLogFile="devopsdayschangelog.json" --url="jdbc:sqlserver://localhost;database=xxx;encrypt=false;" --username=sa --password=yyy generate-changelog`

This will create a child folder, `changeset`, from my directory, but nothing else. Output complains it can't find the liquibase.properties file but otherwise pretends like everything is fine.

![image](https://user-images.githubusercontent.com/106849139/229606288-9048c2d6-aec3-4d8f-a403-d7266edd05b9.png)

**Comment by jnewton03** [comment]
Hi All, Thanks for the reports.  At first glance this sounds like it could be related to the entrypoint: https://github.com/liquibase/docker/blob/main/docker-entrypoint.sh

Anyone in the community willing to take a stab at a PR?

CC @nvoxland @mcred @filipelautert

**Comment by jnewton03** [comment]
@filipelautert between your workaround and the change @nvoxland made in #206 do you think this issue can be closed?

**Comment by filipelautert** [comment]
@jnewton03 yes!

**Comment by rmcelroy-hylaine** [comment]
Hey folks - the post from @filipelautert got me going here on generating changelogs. Thanks!

I wanted to follow up with another question or difficulty. The use of a root changelog is a great best practice mentioned in the official docs:

https://www.liquibase.org/get-started/best-practices

However, mouting sub-directories in volumes isn't straightforward/possible: https://github.com/moby/moby/issues/32582

This command, for instance: `docker run --rm --net="host" -v ${PWD}:/liquibase/changelog -v $PWD/changelogs:/liquibase/changelog/changelogs liquibase/liquibase --defaultsFile=/liquibase/changelog/liquibase.properties --changeLogFile=/changelog/rootchangelog.json update`

Will complain: `Unexpected error running Liquibase: Error parsing /changelog/rootchangelog.json : Could not find directory or directory was empty for includeAll 'changelogs/'`

Any more advice or minor item I'm missing to attach child changelogs and have them be referenceable when executing in a container?
