### ISSUE TITLE
3.10.x/latest JDBC ERROR: Connection could not be created to ... Possibly the wrong driver for the given database URL

### ISSUE THREAD

**Issue by Stonezdev** [liquibase/docker#25]
Hi there, 

I am using the following statement inside the Container created from the Liquibase Docker Image to update my Database.

`/liquibase/liquibase --logLevel=debug --classpath="/liquibase/lib/ojdbc10-19.6.0.0.jar" --driver=oracle.jdbc.OracleDriver --url=jdbc:oracle:thin:@//...... --changeLogFile=/liquibase/changelog/changelog-master.xml --username=${USERNAME} --password=${PASSWORD} update`

When using an older latest Image from the 20th of July,  the execution of the statement (with a valid url)  works without any errors being thrown.
However running **the same**  statement (with a valid url) results in the following ERROR with version latest and 3.10.x.

```
ERROR [liquibase.integration.commandline.Main]: Unexpected error running Liquibase: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  Possibly the wrong driver for the given database URL
liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  Possibly the wrong driver for the given database URL
        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:126)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1338)
        at liquibase.integration.commandline.Main.run(Main.java:300)
        at liquibase.integration.commandline.Main.main(Main.java:159)
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  Possibly the wrong driver for the given database URL
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:259)
        at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:149)
        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:91)
        ... 3 common frames omitted
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  Possibly the wrong driver for the given database URL
        at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:35)
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:256)
        ... 5 common frames omitted
Caused by: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  Possibly the wrong driver for the given database URL
        at liquibase.database.jvm.JdbcConnection.open(JdbcConnection.java:45)
        at com.datical.liquibase.ext.database.jvm.ProJdbcConnection.open(Unknown Source)
        at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:32)
        ... 6 common frames omitted

```

I have already tested ojdbc8-19.3.0.0.0 and ojdbc10-19.3.0.0.0, 19.6.0.0.0, with the same results.

**Comment by r2liquibase** [comment]
We've merged in a PR that *should* resolve this. Can you verify against `latest`? Thanks!

Please reopen if we continue to have issues.
