### ISSUE TITLE
Ojdbc Connection Error Possible fix

### ISSUE THREAD

**Issue by Stonezdev** [liquibase/docker#28]
When using the latest version of the liquibase Image, I am still getting the same error message as mentioned in Issue: https://github.com/liquibase/docker/issues/25 
I am using ojdbc10-19.3.0.0 as the database driver.

```
Unexpected error running Liquibase: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  Possibly the wrong driver for the given database URL
For more information, please use the --logLevel flag
[2020-08-03 18:39:46] SEVERE [liquibase.integration] Unexpected error running Liquibase: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  Possibly the wrong driver for the given database URL
liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  Possibly the wrong driver for the given database URL
        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:127)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1249)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:316)
        at liquibase.Scope.lambda$child$0(Scope.java:159)
        at liquibase.Scope.child(Scope.java:170)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.Scope.child(Scope.java:137)
        at liquibase.Scope.child(Scope.java:183)
        at liquibase.Scope.child(Scope.java:187)
        at liquibase.integration.commandline.Main$1.run(Main.java:315)
        at liquibase.integration.commandline.Main$1.run(Main.java:166)
        at liquibase.Scope.child(Scope.java:170)
        at liquibase.Scope.child(Scope.java:144)
        at liquibase.integration.commandline.Main.run(Main.java:166)
        at liquibase.integration.commandline.Main.main(Main.java:145)
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  Possibly the wrong driver for the given database URL
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:250)
        at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:140)
        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:92)
        ... 14 more
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  Possibly the wrong driver for the given database URL
        at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:36)
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:247)
        ... 16 more
Caused by: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  Possibly the wrong driver for the given database URL
        at liquibase.database.jvm.JdbcConnection.open(JdbcConnection.java:43)
        at com.datical.liquibase.ext.database.jvm.ProJdbcConnection.open(Unknown Source)
        at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:33)
        ... 17 more
```

However when I am using the image including 3.10.x (3.10.2), I suprisingly received an exception I could work with (ORA-01882: timezone region not found). Strangely the logging in Version 3.10.2 seems to be more verbose than in 4.0.0.  
**Setting an environment variable TZ=UTC inside the container fixed this issue for both version 3.10.x and latest.**

```
18:41:43.511 ERROR [liquibase.integration.commandline.Main]: Unexpected error running Liquibase: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  ORA-00604: error occurred at recursive SQL level
ORA-01882: timezone region not found

liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  ORA-00604: error occurred at recursive SQL level
ORA-01882: timezone region not found

        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:125)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1341)
        at liquibase.integration.commandline.Main.run(Main.java:303)
        at liquibase.integration.commandline.Main.main(Main.java:159)
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  ORA-00604: error occurred at recursive SQL level
ORA-01882: timezone region not found

        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:259)
        at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:149)
        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:90)
        ... 3 common frames omitted
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  ORA-00604: error occurred at recursive SQL level
ORA-01882: timezone region not found

        at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:35)
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:256)
        ... 5 common frames omitted
Caused by: liquibase.exception.DatabaseException: Connection could not be created to jdbc:oracle:thin:@//... with driver oracle.jdbc.OracleDriver.  ORA-00604: error occurred at recursive SQL level
ORA-01882: timezone region not found

        at liquibase.database.jvm.JdbcConnection.open(JdbcConnection.java:45)
        at com.datical.liquibase.ext.database.jvm.ProJdbcConnection.open(Unknown Source)
        at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:32)
        ... 6 common frames omitted

```

**Strangely using the Image generated from this Dockerfile including liquibase 4.0.0 does not require an environment variable TZ to be set! It connects to the database with odjbc10-19.3.0.0 without any problems** 
https://github.com/liquibase/docker/commit/290b2735bd97d92f7abbf9552afa2356aae68b46#diff-3254677a7917c6c01f55212f86c57fbf

**Comment by r2liquibase** [comment]
Hi, @Stonezdev ! Are you still having issues?

**Comment by r2liquibase** [comment]
Hi, @Stonezdev . I'm going to close this issues. Thanks!
