### ISSUE TITLE
permission error on changelog when running generateChangeLog

### ISSUE THREAD

**Issue by gm7** [liquibase/docker#35]
I'm attempting to generate the initial change log using the docker image running against an existing Microsoft SQL Database.

Here is a sample docker-compose yaml file to bring up the database
```
version: "3.2"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports:
    - "1433:1433"
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=fakePassw0rd1
    - MSSQL_PID=Developer
    networks:
    - helloworld
    volumes:
    - ./data:/var/opt/mssql/data 
    - ./log:/var/opt/mssql/log 
    - ./secrets:/var/opt/mssql/secrets
    - ./sql:/var/opt/sql

volumes:
  logvolume01: {}

networks:
  helloworld:
```

Now I'm trying to create the initial changelog for a database hosted in the `mssql` service. For simplicity, let's say it is called `AdventureWorks`, and I now run the following liquibase command:
```
docker run --net=host --rm -v /home/grant/liquibase:/liquibase/changelog liquibase/liquibase --url="jdbc:sqlserver://localhost:1433;database=AdventureWorks;" --changeLogFile=/liquibase/changelog/changelog.xml --username=sa --password=fakePassw0rd --logLevel=debug generateChangeLog
```

This gives the following output:
```
...
[2020-09-16 15:52:13] FINE [com.microsoft.sqlserver.jdbc.SQLServerResultSet <init>] SQLServerResultSet:29 created by (SQLServerStatement:29)
[2020-09-16 15:52:13] FINE [com.microsoft.sqlserver.jdbc.SQLServerResultSetMetaData <init>]  SQLServerResultSetMetaData:17 created by (SQLServerResultSet:29)
[2020-09-16 15:52:13] FINE [liquibase.diff] UnexpectedObjectChangeGenerator type order:     liquibase.structure.core.Catalog    liquibase.structure.core.ForeignKey    liquibase.structure.core.Schema    liquibase.structure.core.UniqueConstraint    liquibase.structure.core.View    liquibase.structure.core.Table    liquibase.structure.core.PrimaryKey    liquibase.structure.core.Column    liquibase.structure.core.Index    liquibase.structure.core.Sequence
[2020-09-16 15:52:13] INFO [liquibase.diff] changeSets count: 4
[2020-09-16 15:52:13] INFO [liquibase.diff] /liquibase/changelog/changelog.xml does not exist, creating and adding 4 changesets.
Unexpected error running Liquibase: java.io.FileNotFoundException: /liquibase/changelog/changelog.xml (Permission denied)
For more information, please use the --logLevel flag
[2020-09-16 15:52:13] SEVERE [liquibase.integration] Unexpected error running Liquibase: java.io.FileNotFoundException: /liquibase/changelog/changelog.xml (Permission denied)
liquibase.exception.LiquibaseException: liquibase.command.CommandExecutionException: java.io.FileNotFoundException: /liquibase/changelog/changelog.xml (Permission denied)
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:247)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1359)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:316)
        at liquibase.Scope.lambda$child$0(Scope.java:159)
        at liquibase.Scope.child(Scope.java:170)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.Scope.child(Scope.java:137)
        at liquibase.Scope.child(Scope.java:183)
        at liquibase.Scope.child(Scope.java:187)
        at liquibase.integration.commandline.Main$1.run(Main.java:315)
        at liquibase.integration.commandline.Main$1.run(Main.java:166)
        at liquibase.Scope.child(Scope.java:170)
        at liquibase.Scope.child(Scope.java:144)
        at liquibase.integration.commandline.Main.run(Main.java:166)
        at liquibase.integration.commandline.Main.main(Main.java:145)
Caused by: liquibase.command.CommandExecutionException: java.io.FileNotFoundException: /liquibase/changelog/changelog.xml (Permission denied)
        at liquibase.command.AbstractCommand.execute(AbstractCommand.java:24)
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:245)
        ... 14 more
Caused by: java.io.FileNotFoundException: /liquibase/changelog/changelog.xml (Permission denied)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at java.base/java.io.FileOutputStream.<init>(Unknown Source)
        at liquibase.diff.output.changelog.DiffToChangeLog.printNew(DiffToChangeLog.java:212)
        at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:125)
        at liquibase.Scope.lambda$child$0(Scope.java:159)
        at liquibase.Scope.child(Scope.java:170)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.Scope.child(Scope.java:137)
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:119)
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:86)
        at liquibase.command.core.GenerateChangeLogCommand.run(GenerateChangeLogCommand.java:72)
        at liquibase.command.AbstractCommand.execute(AbstractCommand.java:19)
        ... 15 more
```

The changesets appear to generate correctly, but there is a permission problem when trying to write out the `changelog.xml` file, note the error ` /liquibase/changelog/changelog.xml (Permission denied)`

Am I doing something wrong, or could this be a bug?

**Comment by r2liquibase** [comment]
Your docker container needs to have write permissions to /home/grant/liquibase. Let us know if that works!

**Comment by gm7** [comment]
Unfortunately that made no difference. I have switched to flyway for my project.

> Your docker container needs to have write permissions to /home/grant/liquibase. Let us know if that works!
