### ISSUE TITLE
4.1.1 Liquibase: Unexpected value 'sh' (options must start with a '--')

### ISSUE THREAD

**Issue by acollins74** [liquibase/docker#41]
The 4.1.1 release yesterday introduced a new bug in my pipeline that has been working fine. 
cmd: /liquibase/liquibase --url="jdbc:postgresql://xx.xx.xx.xx:xxxx/XXXXX" --changeLogFile=./files/changelogsql.xml --username=**** --password=**** update

Starting Liquibase at 13:32:39 (version 4.1.1 #10 built at 2020-10-12 19:24+0000)
To display the help, please pass the '--help' option on the command line.
Unexpected error running Liquibase: Unexpected value 'sh' (options must start with a '--')
For more information, please use the --logLevel flag
Oct 28, 2020 1:32:39 PM liquibase.integration
SEVERE: Unexpected error running Liquibase: Unexpected value 'sh' (options must start with a '--')
liquibase.exception.CommandLineParsingException: Unexpected value 'sh' (options must start with a '--')
	at liquibase.integration.commandline.Main.parseOptions(Main.java:1154)
	at liquibase.integration.commandline.Main$1.run(Main.java:259)
	at liquibase.integration.commandline.Main$1.run(Main.java:193)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:145)
	at liquibase.integration.commandline.Main.run(Main.java:193)
	at liquibase.integration.commandline.Main.main(Main.java:156)
Cleaning up file based variables
00:00
ERROR: Job failed: exit code 255

I have confirmed 3.10.x still works as expected.

**Comment by r2liquibase** [comment]
Is this still an issue with the latest release @acollins74 ? Thanks!
